### ISSUE TITLE
Move schema designer button closer to keyspace button

### ISSUE THREAD

**Issue by samlaws** [vaticle/typedb-studio#169]
## Problem to Solve

Currently, the button to change between the schema and query view is on the far left of the toolbar on the opposite side of the screen to the keyspace selection button. This is a bit annoying in general but I noticed it especially when doing a demo where I had to constantly swap between different schemas and queries especially on a trackpad.

## Current Workaround

N/A

## Proposed Solution

![Proposed solution](https://user-images.githubusercontent.com/48316473/62291285-76394880-b45b-11e9-8994-cf0f68d860b7.PNG)

Move the button to be with the others.

## Additional Information

N/A

**Comment by jmsfltchr** [comment]
@samlaws also mentioned that when opening the schema designer the user also has to select a keyspace. This means that to open the schema designer and select a keyspace they must traverse the whole width of the screen at least once, likely twice since most user interaction outside of the visualisation takes place on the right-hand side.

**Comment by alexjpwalker** [comment]
This issue is no longer relevant in Studio as the relevant buttons don't exist anymore.
