### ISSUE TITLE
How to install and start Grakn Workbase

### ISSUE THREAD

**Issue by jagadeesh93** [vaticle/typedb-studio#338]
## Problem to Solve

Please give basic steps how to install and run wokrkbase on ubuntu machine .

**Comment by ivyleavedtoadflax** [comment]
Yes please - remarkable to find no instructions anywhere, even in the tar.gz

**Comment by ivyleavedtoadflax** [comment]
That said @jagadeesh93  if you execute the `grakn-workbase` from within the tar archive it seems to work!

**Comment by alexjpwalker** [comment]
We have moved from Workbase to Studio. Studio is pretty straightforward to install on Ubuntu (just download the DEB file and follow the instructions at https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt ).

Nonetheless, I've raised https://github.com/vaticle/docs/issues/574 so that we properly document the installation of Studio.
