### ISSUE TITLE
Schema view filters

### ISSUE THREAD

**Issue by gitvge** [vaticle/typedb-studio#348]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Problem to Solve

When viewing a schema, the display setting allows only to control entity, attributes and relations as a whole, but not conceptual parts. This is problematic for large complex schemas when creating screenshots thereof for documentation purpose.

## Current Workaround

none

## Proposed Solution

Allow display settings related to the schema.

## Additional Information

-

**Comment by alexjpwalker** [comment]
We've rebuilt Workbase from scratch, creating a new application, TypeDB Studio, which should make adding features much easier.

What do you mean by "display settings related to the schema"? Workbase already allows you to configure the display setting for any Type, not just `entity`/`attribute`/`relation`. What other criteria would you like to see? Are you just looking for a way to select a particular answer in the graph and say "I want to change the appearance of just this one answer", or perhaps selecting a rectangular region?

(For bookkeeping purposes I'm closing this issue because it's over a year old, but please **reopen** the issue if it is still relevant to you!)
