### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-studio#392]
We don't currently have automated tests for Studio, which may lead to missed bugs and regressions in the future.

**Comment by jamesreprise** [comment]
Our progress so far:
- compose-jb's testing framework is in its infancy. Aspects of the framework like being able to see windows and their composables as a part of the composable tree aren't there at the moment, so we'll need to manually edit the state of the program in those cases.
   - A lot of usages of window are solely for calculating height and width, which is overkill. Instead, we should just pass them height and width.
- Once we've refactored out Window usages for the above, it should be easier to create a mock studio composable that can be tested. 
- We want to remove friction from the process of creating a mock studio composable as much as possible so that tests can be carried out from release to release with as little manual work as possible.

**Comment by jamesreprise** [comment]
We have some experimental behaviour testing as demonstrated here:
https://github.com/jamesreprise/typedb-studio/blob/mock-studio/test/Experiment.kt

This experiment has a couple of issues:
- Liberal use of delay()
- Only tests state rather than using only state modification to bridge the gaps in compose-jb's testing framework and performing clicks on nodes for everyting else.

Merging this into upstream:master will be a bit of a project as this only runs with a modified Studio object that is contained within a `Column` at the root rather than a `Window`. Some stub window class might well be needed to be manually substituted in when we want to test before a release.

**Comment by jamesreprise** [comment]
We've made a lot of progress on this. See https://github.com/vaticle/typedb-studio/pull/598.

**Comment by jamesreprise** [comment]
Our first PR is now live on the development branch! 

We're working on expanding the foundation that has been laid into fully fledged test suite.

**Comment by jamesreprise** [comment]
Once the above PR is merged, I'll close this issue - but we'll continue to develop more (particularly regression) tests in the future.

**Comment by jamesreprise** [comment]
Merged! Closing this issue.
